#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew..."
  ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)
  brew update

echo "Installing GIT and lots of other stuff"
  brew install git ack wget curl redis memcached libmemcached colordiff imagemagick icoutils

echo "Checking out dotfiles and letting it do its stuff..."
	git clone git://github.com/javierjulio/dotfiles.git ~/workspaces/dotfiles
	cd ~/workspaces/dotfiles
	rake install
	reload

echo "Adding Sublime Text CLI"
  sudo mkdir -p "/usr/local/bin/" && ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" "/usr/local/bin/subl"


./osx
